#!/bin/bash
# testing the for in Alabama Alaska Arizona Arkansas California Colorado
for test in Alabama Alaska Arizona Arkansas California Colorado
do 
echo "The next state is $test"
done
test=Connecticut
echo "Wait, now we're visiting $test"
